
/*********************************************************************************************

    This is public domain software that was developed by or for the U.S. Naval Oceanographic
    Office and/or the U.S. Army Corps of Engineers.

    This is a work of the U.S. Government. In accordance with 17 USC 105, copyright protection
    is not available for any work of the U.S. Government.

    Neither the United States Government, nor any employees of the United States Government,
    nor the author, makes any warranty, express or implied, without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, or assumes any liability or
    responsibility for the accuracy, completeness, or usefulness of any information,
    apparatus, product, or process disclosed, or represents that its use would not infringe
    privately-owned rights. Reference herein to any specific commercial products, process,
    or service by trade name, trademark, manufacturer, or otherwise, does not necessarily
    constitute or imply its endorsement, recommendation, or favoring by the United States
    Government. The views and opinions of authors expressed herein do not necessarily state
    or reflect those of the United States Government, and shall not be used for advertising
    or product endorsement purposes.
*********************************************************************************************/


/****************************************  IMPORTANT NOTE  **********************************

    Comments in this file that start with / * ! or / / ! are being used by Doxygen to
    document the software.  Dashes in these comment blocks are used to create bullet lists.
    The lack of blank lines after a block of dash preceeded comments means that the next
    block of dash preceeded comments is a new, indented bullet list.  I've tried to keep the
    Doxygen formatting to a minimum but there are some other items (like <br> and <pre>)
    that need to be left alone.  If you see a comment that starts with / * ! or / / ! and
    there is something that looks a bit weird it is probably due to some arcane Doxygen
    syntax.  Be very careful modifying blocks of Doxygen comments.

*****************************************  IMPORTANT NOTE  **********************************/



using namespace std;  // Windoze bullshit - God forbid they should follow a standard


QString exitSaveText = 
  areaCheck::tr ("<img source=\":/icons/exit_save.png\"> Click this button to exit after saving changes to all "
                 "area or zone files that have been modified.");

QString exitNoSaveText = 
  areaCheck::tr ("<img source=\":/icons/exit_no_save.png\"> Click this button to exit without saving any changes "
                 "to area or zone files that have been modified.");

QString fileText = 
  areaCheck::tr ("<img source=\":/icons/fileopen.png\"> Click this button to open input files.");

QString zoomOutText = 
  areaCheck::tr ("<img source=\":/icons/icon_zoomout.png\"> Click this button to zoom out one level.");
QString zoomInText = 
  areaCheck::tr ("<img source=\":/icons/icon_zoomin.png\"> Click this button to define a rectangular zoom area.  "
                 "After clicking the button the cursor will change to the zoom cursor "
                 "<img source=\":/icons/zoom_cursor.png\">.  "
                 "Click the left mouse button to define a starting point for a rectangle.  Move the mouse to "
                 "define the zoom in bounds.  To finish and zoom in, simply click the left mouse button again.  To "
                 "abort the zoom in operation click the middle mouse button or right click and select an option from "
                 "the menu.");

QString coastText = 
  areaCheck::tr ("<img source=\":/icons/coast.png\"> Click this button to toggle the display of coastline on and off.");

QString prefsText = 
  areaCheck::tr ("<img source=\":icons/prefs.png\"> Click this button to change program preferences.");


QString stopText = 
  areaCheck::tr ("<img source=\":icons/stop.png\"> Click this button to cancel drawing.");


QString mapText = 
  areaCheck::tr ("The areaCheck program is used to display and edit ISS60 and generic area and zone files, "
                 "and Army Corps area files.  It can also be used to display track files generated by the trackLine "
		 "program, GeoTIFF files, ESRI polygon shape files, Binary Feature Data (.bfd) files, LLZ files, "
		 "YXZ files, CHRTR .fin files, CHRTR2 .ch2 files, and BAG files.  Loading area, zone, or track files is as simple "
                 "as clicking on the <img source=\":icons/fileopen.png\"> icon and then selecting the desired file or "
		 "files.  Context sensitive help is available for all actions by "
		 "using the What's This button <img source=\":icons/contextHelp.png\">.<br><br>"
                 "The default action for the program is zoom in <img source=\":icons/icon_zoomin.png\">.  No editing "
                 "functions will be available until one or more zone or area files are loaded.");

QString areaCheckAboutText = 
  areaCheck::tr ("<center><br>areaCheck<br><br>"
                 "Author : Jan C. Depner (area.based.editor@gmail.com)<br>"
                 "Date : 26 June 2005<br><br></center>") + mapText;

QString rectText = 
  areaCheck::tr ("<img source=\":icons/edit_rect.png\"> This button allows the user to define a rectangular area and "
                 "output it to an area or zone file (*.ARE, *.are, *.zne, *.ZNE, *.tdz).  When selected the cursor will "
                 "become the define rectangle cursor <img source=\":icons/edit_rect_cursor.png\">.  Left clicking on a "
                 "location will cause that point to be the rectangle anchor point.  Moving the cursor will cause a "
                 "rectangle to appear.  To finalize the rectangle left click on a location.  At that time a file "
                 "selection dialog will pop up.  Enter a file name or use a preexisting file.  File type will be defined "
                 "by the filter (*.ARE, *.are, *.zne, *.ZNE, *.tdzs must have a .are extension.  If you do not put an "
                 "extension on the file it will be appended automatically.  If, at any time during the operation you wish "
                 "to discard the rectangle and abort the operation simply click the middle mouse button.");

QString polyText = 
  areaCheck::tr ("<img source=\":icons/edit_poly.png\"> This button allows the user to define a polygonal area and output "
                 "it to an area or zone file (*.ARE, *.are, *.zne, *.ZNE, *.tdz).  When selected the cursor will become "
                 "the define polygon cursor <img source=\":icons/edit_poly_cursor.png\">.  Left clicking on a location "
                 "will cause that point to be a polygon vertex.  Moving the cursor will cause a line to appear.  Select "
                 "the next vertex by left clicking on a location again.  Select as many points as needed.  To select the "
                 "last point double click on its location.  At that time a file selection dialog will pop up.  Enter a "
                 "file name or use a preexisting file.  File type will be defined by the filter (*.ARE, *.are, "
                 "*.zne, *.ZNE, *.tdz).  If you do not put an extension on the file it will be appended automatically.  "
                 "If, at any time during the operation you wish to discard the rectangle and abort the operation simply "
                 "click the middle mouse button.");

QString addVertexText = 
  areaCheck::tr ("<img source=\":icons/add_vertex.png\"> This button allows the user to add a vertex to an area.  When "
                 "the button is pressed the cursor will become the add vertex cursor "
                 "<img source=\":icons/add_vertex_cursor.png\"> and the nearest line to the cursor will be highlighted "
                 "(Hint: move the cursor close to the vertices of the area).  When the desired line segment is "
                 "highlighted press the left mouse button to add a point to the line.  When pressed the cursor will "
                 "become the cross cursor and a dot will follow the cursor.  When the dot is in the desired location "
                 "press the left mouse button to add it to the highlighted line segment.  Press the middle mouse button "
                 "to discard the point.");

QString deleteVertexText = 
  areaCheck::tr ("<img source=\":icons/delete_vertex.png\"> This button allows the user to delete a vertex from an area.  "
                 "When the button is pressed the cursor will become the delete vertex cursor "
                 "<img source=\":icons/delete_vertex_cursor.png\"> and the nearest vertex to the cursor will be "
                 "highlighted.  When the desired vertex is highlighted press the left mouse button to delete the vertex.");

QString moveVertexText = 
  areaCheck::tr ("<img source=\":icons/move_vertex.png\"> This button allows the user to move a vertex in an area.  When "
                 "the button is pressed the cursor will become the move vertex cursor "
                 "<img source=\":icons/move_vertex_cursor.png\"> and the nearest vertex to the cursor will be "
                 "highlighted.  When the desired vertex is highlighted press the left mouse button to select the vertex.  "
                 "The cursor will become the cross cursor and a dot will appear at the cursor.  Move the cursor/dot to "
                 "the desired new location for the highlighted vertex and press the left mouse button to place the "
                 "vertex.  To discard the point click the right mouse button.");

QString editVertexText = 
  areaCheck::tr ("<img source=\":icons/edit_vertex.png\"> This button allows the user to manually edit a vertex location "
                 "for an area.  When the button is pressed the cursor will become the edit vertex cursor "
                 "<img source=\":icons/edit_vertex_cursor.png\"> and the nearest vertex to the cursor will be "
                 "highlighted.  When the desired vertex is highlighted press the left mouse button to pop up the edit "
                 "widget.  The latitude and longitude of the vertex will be in the position format defined in the "
                 "preferences dialog.  You may use any of the standard position formats:<br><br>"
                 "<ul>"
                 "<li>Hemisphere Degrees decimal                 : S 28.4532</li>"
                 "<li>Hemisphere Degrees minutes decimal         : S 28 27.192</li>"
                 "<li>Hemisphere Degrees minutes seconds decimal : S 28 27 11.52</li>"
                 "<li>Signed Degrees decimal                 : -28.4532</li>"
                 "<li>Signed Degrees minutes decimal         : -28 27.192</li>"
                 "<li>Signed Degrees minutes seconds decimal : -28 27 11.52</li>"
                 "</ul>"
                 "West longitude and south latitude are negative :<br><br>"
                 "Press the <b>Apply</b> button to apply the change.  Press <b>Cancel</b> button to discard the changes.");

QString moveAreaText = 
  areaCheck::tr ("<img source=\":icons/move_area.png\"> This button allows the user to move an area.  When the button is "
                 "pressed the cursor will become the move area cursor <img source=\":icons/move_area_cursor.png\"> and "
                 "the nearest area to the cursor will be highlighted.  (Hint: move the cursor close to one of the "
                 "vertices of the area).  When the desired area is highlighted press the left mouse button to select the "
                 "area.  You may then move the area to the desired location and press the left mouse button to place the "
                 "area.  To discard the move click the middle mouse button or right click and select an option from the "
                 "menu.");

QString copyAreaText = 
  areaCheck::tr ("<img source=\":icons/copy_area.png\"> This button allows the user to copy an area.  When the button is "
                 "pressed the cursor will become the copy area cursor <img source=\":icons/copy_area_cursor.png\"> and "
                 "the nearest area to the cursor will be highlighted.  (Hint: move the cursor close to one of the "
                 "vertices of the area).  When the desired area is highlighted press the left mouse button to select the "
                 "area.  You may then move the duplicate area to the desired location and press the left mouse button to "
                 "place the area.  A file selection dialog will appear to allow you to place the new area/zone file "
                 "wherever you wish.  To discard the move click the middle mouse button or right click to select an "
                 "option from the menu.");

QString linkText = 
  areaCheck::tr ("<img source=\":/icons/unlink.png\"> Click this button to choose from other ABE or geographical GUI "
		 "programs to connect to.  At present the only possible applications are pfmView, fileEdit3D, and "
		 "areaCheck.  Hopefully, in the near future, we will be adding CNILE to the list.  The connection "
		 "allows cursor tracking and limited data exchange between the applications.  If there are no "
		 "available ABE groups to link to you can create a new group and add yourself to it so that other "
		 "applications can link to this one.");

QString unlinkText = 
  areaCheck::tr ("<img source=\":/icons/link.png\"> Click this button to disconnect from another ABE or "
		 "geographical GUI program.  This option is not available unless you have already linked to another "
		 "program.");

QString statusBarText = 
  areaCheck::tr ("The status bar displays information about cursor position in the "
                 "main window.  Most of the fields are fixed with the exception of the far right "
                 "field.  This is used for miscellaneous messages.");

QString messageText = 
  areaCheck::tr ("This menu option will display a dialog containing any nonfatal error messages from this program.");


